"""add foreign key to Review

Revision ID: 800fcfb1e80f
Revises: bd22fb2ead2a
Create Date: 2024-06-11 16:53:18.926473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800fcfb1e80f'
down_revision = 'bd22fb2ead2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_employee_id_employees'), 'reviews', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'employee_id')
    # ### end Alembic commands ###
